Introduction
mojaloop/reference-architecture-doc pull request #27
Opened 2021-09-06 14:57 UTC by pedrosousabarreto

This is the initial version of the intro.

Next will be a merge with of the intro text on the Reference Architecture section, that should be move to the intro section.

2021-09-07 13:14 UTC, mdebarros requested changes
Hey @pedrosousabarreto,

I have 3 major issues that need to be fixed:

1. Merge conflict;
2. Duplicate menu config; and
3. Missing notes

The rest are mostly suggestions on how the wording can be simplified, or changed to clarify the idea.

Have a look, and let me know your thoughts.

2021-09-07 13:14 UTC, mdebarros commented on docs/introduction/README.md
> +* Supporting subdomains - these are problems that can’t be easily solved by using off-the-shelf software, we’ll need some coding effort to solve them, it’s not just integration. Examples of this are
```suggestion
* Supporting subdomains - This domain category provides ancillary functions that are required by the business domain. The problems within this category can generally be solved by integrating off-the-shelf software with some coding effort. Examples of this are Authorization and Access Policies or Reporting
```

2021-09-07 13:14 UTC, mdebarros commented on docs/introduction/README.md
> +* Generic subdomains - these are usually problems that can be solved using of-the-shelf software, requiring only some integration effort. Examples are Authentication or Platform monitoring, we don’t
```suggestion
* Generic subdomains - Similar to the Supporting subdomain, except these problems are primarily solved by integrating off-the-shelf software that requires very little (if any at all) coding effort. Examples are Authentication or Platform monitoring, we don’t need to code these solutions ourselves but we still have to design accordingly
```

2021-09-07 22:57 UTC, pedrosousabarreto commented on docs/introduction/README.md
> +The Reference Architecture creation process has been guided by Domain-Driven Design[1] principles and the solution space heavily inspired by SOLID's[2] single responsibility principle (SRP).
This was copies from Michael's section.. the part we need to merge with later.

2021-09-07 23:00 UTC, pedrosousabarreto commented on docs/introduction/README.md
> +* Core subdomains - we need to solve these problems ourselves to control the outcome. In practical terms, this is where we put the most effort. Examples are transfers, participant lifecycle managemen
This not accurate, but I'll come to this later.

2021-09-07 23:01 UTC, pedrosousabarreto commented on docs/introduction/README.md
> +* Supporting subdomains - these are problems that can’t be easily solved by using off-the-shelf software, we’ll need some coding effort to solve them, it’s not just integration. Examples of this are
same

2021-09-07 23:04 UTC, pedrosousabarreto commented
Thanks for the review, accepted most. Some require a bit more thinking (copied from slides).
This was just a draft submission just to push my changes while out-of-office

2021-09-07 23:15 UTC, pedrosousabarreto commented on docs/.vuepress/config.js
> +        text: 'Introduction',
I'm not following.. The first is the nav bar on top, the second is the sidebar.

2021-09-15 12:31 UTC, pedrosousabarreto commented
Fixed the merge conflict in docs/introduction/README.md

2021-09-15 12:51 UTC, mdebarros approved these changes
+1

2021-09-15 14:35 UTC, merged