Security Bounded documentation
mojaloop/reference-architecture-doc pull request #44
Opened 2021-12-06 12:17 UTC by bukasaaime

Security BC

1. Overview
2. User / Operator login (AuthN)
3. Authorization Model
4. BC bootstrap
5. BC startup
6. Role / Privilege association
7. Example Query / call

2021-12-06 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mojaloop/reference-architecture-doc?pullRequest=44) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mojaloop/reference-architecture-doc?pullRequest=44) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mojaloop/reference-architecture-doc?pullRequest=44) it.</sub>

2022-01-12 08:23 UTC, mdebarros requested changes
A couple of comments.

Please make sure there are no spaces in the image names.

Also please be consistent with the file naming conventions. I see snake-case being used, and then another with spaces, and another with camel-case.

Note Camel-case is prefered.

2022-01-12 08:26 UTC, mdebarros requested changes
I have added some comments.

Also, I recommend being consistent with the file naming conventions. I see snake-case, camel-case and one even with space for the image names. Our preference is camel-case, so please be consistent here.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +![Use Case - Example REPLACE ME](./assets/securityBCv0.3.png)
Please change the info text for the image to something more useful then the default template `Use Case - Example REPLACE ME`.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +![Use Case - Example REPLACE ME](./assets/securityBCv0.8.png)
Please change the info text for the image to something more useful then the default template `Use Case - Example REPLACE ME`.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +![Use Case - Example REPLACE ME](./assets/securityBCv0.4.png)
Please change the info text for the image to something more useful then the default template `Use Case - Example REPLACE ME`.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +![Use Case - Example REPLACE ME](./assets/bc_start_up.png)
Please change the info text for the image to something more useful then the default template `Use Case - Example REPLACE ME`.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +![Use Case - Example REPLACE ME](./assets/securityBCv0.6.png)
Please change the info text for the image to something more useful then the default template `Use Case - Example REPLACE ME`.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +![Use Case - Example REPLACE ME](./assets/securityBCv0.7.png)
Please change the info text for the image to something more useful then the default template `Use Case - Example REPLACE ME`.

2022-01-12 08:26 UTC, mdebarros commented on docs/refarch/boundedContexts/security/index.md
> +| IAM | Identity and Access Management. Adapter that will provide services for menus, profiles, roles and permissions.  |
I would suggest adding the following terms to this table:

- AuthN
- AuthZ
- JWT
- KMS

2022-01-31 11:51 UTC, pedrosousabarreto approved these changes
Looks good for a first version, we can publish it now and tune it later.

2022-01-31 11:52 UTC, mdebarros approved these changes

2022-01-31 13:22 UTC, pedrosousabarreto commented
Due to the structure change in main, these changes where cherry picked to a separate PR and have already being merged to main. 
Closing.

2022-01-31 13:22 UTC, closed without merging