Mwmentor/example
mojaloop/reference-architecture-doc pull request #7
Opened 2021-08-16 15:07 UTC by mwmentor

This is an update to the ML 2.0 Ref. Arch. Doc. that we are working on presently.  It is referenced as 20210816a.

2021-08-16 15:10 UTC, mwmentor commented
Ready for review.

2021-08-16 15:18 UTC, mdebarros requested changes
A couple of changes.

Let's discuss it tomorrow morning.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p style="color: red; font-weight: bold">>>>>>  gd2md-html alert:  ERRORs: 0; WARNINGs: 0; ALERTS: 5.</p>
We can remove this. This looks like a warning from the converter.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<ul style="color: red; font-weight: bold"><li>See top comment block for details on ERRORs and WARNINGs. <li>In the converted Markdown or HTML, search for inline alerts that start with >>>>>  gd2md-ht
We can remove this. This looks like a warning from the converter.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p style="color: red; font-weight: bold">Links to alert messages:</p><a href="#gdcalert1">alert1</a>
We can remove this. This looks like a warning from the converter.

Same with these "alert" lines.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p style="color: red; font-weight: bold">>>>>> PLEASE check and correct alert issues and delete this message and the inline alerts.<hr></p>
We can remove this. This looks like a warning from the converter.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p id="gdcalert2" ><span style="color: red; font-weight: bold">>>>>>  gd2md-html alert: inline image link here (to images/image2.png). Store image on your image server and adjust path/filename/extens
To be replaced with the missing image.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p id="gdcalert3" ><span style="color: red; font-weight: bold">>>>>>  gd2md-html alert: inline image link here (to images/image3.png). Store image on your image server and adjust path/filename/extens
To be replaced with the missing image.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p id="gdcalert4" ><span style="color: red; font-weight: bold">>>>>>  gd2md-html alert: inline image link here (to images/image4.png). Store image on your image server and adjust path/filename/extens
To be replaced with the missing image.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<p id="gdcalert5" ><span style="color: red; font-weight: bold">>>>>>  gd2md-html alert: inline image link here (to images/image5.png). Store image on your image server and adjust path/filename/extens
To be replaced with the missing image.

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<table>
Table to be converted to markdown --> https://www.markdownguide.org/extended-syntax/#tables

We can try use this tool to convert them --> https://jmalarcon.github.io/markdowntables/

2021-08-16 15:18 UTC, mdebarros commented on vuepress/docs/refarch/README.md
> +<table>
Table to be converted to markdown --> https://www.markdownguide.org/extended-syntax/#tables

We can try use this tool to convert them --> https://jmalarcon.github.io/markdowntables/

2021-08-16 15:33 UTC, mwmentor commented
Okay - let's just dump this push - it was just a test to see that I had the process ok.  I see lots of changes - no worries, I will get them done... thanks :-)

2021-08-17 08:34 UTC, mdebarros approved these changes
+1

2021-08-17 08:39 UTC, merged